version: '3'
services:
  web:
    container_name: 'reconness'
    image: 'reconness'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:5000'
    depends_on:
      - 'postgres'
      - 'rabbitmq'
    networks:
      - reconness-network
    environment:
      - ReconnessUserName=reconness               # login username
      - ReconnessPassword=reconness               # login password
      - PostgresUser=reconness                    # postgres userName
      - PostgresPassword=reconness                # postgres password
      - PostgresDb=reconness                      # postgres database
      - SecurityKey=mysecuritykeypleasechangethis # securityKey for the JWT, minimum length is 16 characters

  postgres:
    ports:
      - '5432:5432'
    container_name: 'reconness-postgresql'
    environment:
        POSTGRES_USER: 'reconness'                # postgres username, needs to be the same defined above 
        POSTGRES_PASSWORD: 'reconness'            # postgres password, needs to be the same defined above 
        POSTGRES_DB: 'reconness'                  # postgres database, needs to be the same defined above 
    volumes:
      - 'reconness-postgresql-volume:/var/lib/postgresql'
    image: 'postgres:latest'
    networks:
      - reconness-network

  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    container_name: 'reconness-rabbitmq'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - reconness-network

volumes:
    reconness-postgresql-volume:

networks:
    reconness-network:
        driver: bridge
